apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-pipeline-config
  namespace: dev
  labels:
    app.kubernetes.io/name: contoso-air-pipeline
    kubernetes.azure.com/generator: devhub
data:
