apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-pipeline-v2
  labels:
    app.kubernetes.io/name: data-pipeline-v2
    app.kubernetes.io/part-of: data-pipeline-v2-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: data-pipeline-v2