apiVersion: v1
kind: Service
metadata:
  name: data-pipeline-v2
  namespace: namespace-workflow-1789710278219
  labels:
    app.kubernetes.io/name: data-pipeline-v2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: data-pipeline-v2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000